name: Test
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        java: [17, 19]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
          cache: 'gradle'
      - run: ./gradlew checkLicenses generateQmj --parallel --stacktrace
      - run: ./gradlew check build publishToMavenLocal --stacktrace --parallel
      - run: mkdir run && echo "eula=true" >> run/eula.txt
      - run: ./gradlew :runAutoAllTestServer :runGameAllTestServer --stacktrace
      - uses: actions/upload-artifact@v3
        with:
          name: Production Mods
          path: |
            ./**/build/libs/
            !./build-logic/**
            !./**/build/libs/*-javadoc.jar
            !./**/build/libs/*-sources.jar
            !./**/build/libs/*-testmod.jar
      - uses: actions/upload-artifact@v3
        with:
          name: Test Mods
          path: ./**/build/libs/*-testmod.jar
