name: Test
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        # Keep the matrix for when jdk 17 rc come out
        java: [17]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
      - uses: actions/checkout@v2
      - run: ./gradlew checkLicenses generateQmj --parallel --stacktrace
      - run: ./gradlew check build publishToMavenLocal --stacktrace --parallel
      - run: mkdir run && echo "eula=true" >> run/eula.txt
      - run: ./gradlew :runAutoTestServer --stacktrace
      - uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: ./*/build/libs/
